# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Docker Build and Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # Change to your AWS region

      # ✅ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ✅ Log in to AWS ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # ✅ Build and Tag Docker Image
      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-first-dockerproject:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-first-dockerproject:latest 307946647513.dkr.ecr.ap-southeast-2.amazonaws.com/my-first-dockerproject:latest

      # ✅ Push Image to Docker Hub
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-first-dockerproject:latest

      # ✅ Push Image to AWS ECR
      - name: Push image to AWS ECR
        run: docker push 307946647513.dkr.ecr.ap-southeast-2.amazonaws.com/my-first-dockerproject:latest

      # ✅ Ensure ECS Cluster Exists
      - name: Ensure ECS Cluster Exists
        run: |
            aws ecs describe-clusters --clusters my-cluster --region ap-southeast-2 || \
            aws ecs create-cluster --cluster-name my-cluster --region ap-southeast-2

      # ✅ Deploy Updated Image to ECS
      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster my-cluster \
          --service my-ecs-service \
          --force-new-deployment






