# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Docker Build and Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # Change to your AWS region

      # ✅ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ✅ Log in to AWS ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # ✅ Build and Tag Docker Image
      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-first-dockerproject:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-first-dockerproject:latest 307946647513.dkr.ecr.ap-southeast-2.amazonaws.com/my-first-dockerproject:latest

      # ✅ Push Image to Docker Hub
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-first-dockerproject:latest

      # ✅ Push Image to AWS ECR
      - name: Push image to AWS ECR
        run: docker push 307946647513.dkr.ecr.ap-southeast-2.amazonaws.com/my-first-dockerproject:latest

      # ✅ Ensure ECS Cluster Exists
      - name: Ensure ECS Cluster Exists
        run: |
          CLUSTER_STATUS=$(aws ecs describe-clusters --clusters my-cluster --region ap-southeast-2 --query "clusters[0].status" --output text 2>/dev/null || echo "MISSING")
          if [[ "$CLUSTER_STATUS" == "MISSING" ]]; then
            echo "Creating ECS cluster..."
            aws ecs create-cluster --cluster-name my-cluster --region ap-southeast-2
          else
            echo "ECS cluster already exists."
          fi

      # ✅ Register ECS Task Definition
      - name: Register ECS Task Definition
        run: |
          cat <<EOF > task-def.json
          {
            "family": "my-task-definition",
            "containerDefinitions": [
              {
                "name": "my-container",
                "image": "307946647513.dkr.ecr.ap-southeast-2.amazonaws.com/my-first-dockerproject:latest",
                "memory": 512,
                "cpu": 256,
                "essential": true
              }
            ]
          }
          EOF
          aws ecs register-task-definition --cli-input-json file://task-def.json

      # ✅ Ensure ECS Service Exists
      - name: Ensure ECS Service Exists
        run: |
          SERVICE_COUNT=$(aws ecs list-services --cluster my-cluster --region ap-southeast-2 --query "serviceArns" --output text | wc -w)
          if [[ "$SERVICE_COUNT" -eq 0 ]]; then
              echo "Creating ECS service..."
              LATEST_TASK_DEF=$(aws ecs describe-task-definition --task-definition my-task-definition --query "taskDefinition.taskDefinitionArn" --output text)
              
              aws ecs create-service \
                --cluster my-cluster \
                --service-name my-ecs-service \
                --task-definition "$LATEST_TASK_DEF" \
                --desired-count 1 \
                --launch-type FARGATE \
                --network-configuration "awsvpcConfiguration={subnets=[subnet-05ed08580ad610535],securityGroups=[sg-08c6b2beed556f426],assignPublicIp=ENABLED}"
          else
            echo "ECS service already exists."
          fi

      # ✅ Deploy Updated Image to ECS
      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster my-cluster \
          --service my-ecs-service \
          --force-new-deployment







